# Generated by Django 5.1.6 on 2025-03-18 19:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
