# Generated by Django 5.1.6 on 2025-03-18 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_category_userprofile_terms_accepted_poi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='category',
        ),
        migrations.RemoveField(
            model_name='poi',
            name='category',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='traveler',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='points_of_interest',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='traveler',
        ),
        migrations.RemoveField(
            model_name='ticketresponse',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='ticketresponse',
            name='responder',
        ),
        migrations.RemoveField(
            model_name='traveler',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='collaborators',
        ),
        migrations.RemoveField(
            model_name='travelerverification',
            name='traveler',
        ),
        migrations.RemoveField(
            model_name='travelernote',
            name='traveler',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='traveler',
        ),
        migrations.RemoveField(
            model_name='travelernote',
            name='author',
        ),
        migrations.RemoveField(
            model_name='travelerverification',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CalendarSync',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Itinerary',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='POI',
        ),
        migrations.DeleteModel(
            name='SupportTicket',
        ),
        migrations.DeleteModel(
            name='TicketResponse',
        ),
        migrations.DeleteModel(
            name='Traveler',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.DeleteModel(
            name='TravelerNote',
        ),
        migrations.DeleteModel(
            name='TravelerVerification',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
