# Generated by Django 5.1.6 on 2025-03-19 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='terms_accepted',
        ),
    ]
